
app_name: 'gwserver'
project_name: 'dtu-manager-gateway'
project_version: '0.1'

logging:
  level: DEBUG
  format: '%(levelname)s %(asctime)s  %(message)s'
  message_format: '%(project_name)s:%(project_version)s %(app_id)s %(_filename)s:%(_lineno)d [%(tags)s] '

  filters:
    trans:
      tag: 'TRANS:'   # tag 过滤
  handlers:
    - type: file
      enable: true
      filename: 'server.log'
      encoding: 'UTF-8'
      max_bytes: 67108864 # 64MB
      backup_count: 10

    - type: console
      enable: true

http_trace: #自动日志记录
  level: DEBUG
  request:
    options:
      header:  false
      body:  true
      max_size: 500 # 最大数据包长度
    urls:
      - match: '/'
      - match: 'zoo/cat'
        body:  true

  response:
    options:
      header:  false
      body:  true
      max_size: 500 # 最大数据包长度
    urls:
      - match: '/'
      - match: 'zoo/cat'
        body:  true

datasources:
  - name: 'mongodb'
    class: 'mantis.fundamental.nosql.mongo.Datasource'
    host: 'localhost'
    port: 27017
    dbname:
    user:
    password:
    enable: false

  - name: 'zk_1'
    type: 'zookeeper'
    enable: false
    hosts: 'localhost:2181'
    root: '/camel'

  - name: 'redis'
    class: 'mantis.fundamental.redis.datasource.Datasource'
    host: 'localhost'
    port: 6379
    password: ''
    db: 0
    enable: false

message_brokers:
  - name: 'kafka'
    class: 'mantis.fundamental.kafka.broker.MessageBroker'
    enable: true
    hosts: 'server1:9092'
    zookeepers: 'server1:2181'
    channels:
      - name: 'dtu_topic'
        group: ''  # simple_consumer if group is null
        handler:  'mantis.yinlian.iot.mx.get_message' # last unit< get_message> is function object
        enable: true
        type: 'queue'
      - name: 'test-topic-up'
        group: ''
        enable: true
        type: 'queue'

  - name: 'redis'
    class: 'mantis.fundamental.redis.broker.MessageBroker'
    host: '127.0.0.1'
    port: 6379
    password: ''
    db: 0
    enable: true
    channels:
      - name: 'iot_data_chan'
        handler: 'handlers.iot.get_message'
        enable: false
        type: 'pubsub' # or queue

services:
  - name: 'http'
    class: 'mantis.fundamental.flask.service.FlaskService'
    enable: false
    block: false
    cfgs:
      SQLALCHEMY_DATABASE_URI : 'sqlite:////tmp/test.db'
      SQLALCHEMY_BINDS:
      SQLALCHEMY_TRACK_MODIFICATIONS : true
      SQLALCHEMY_COMMIT_ON_TEARDOWN : true
      SECRET_KEY : "abc"
      TEMPLATES_AUTO_RELOAD: true
      DEBUG: true
      SEND_FILE_MAX_AGE_DEFAULT: 0
    http:
#      host : '172.16.109.237'
      host : ''
      port : 19002
      threaded: false
      debug: true

    blueprints:
      - package: 'http'
        url: '/'
        name: 'http'
        register: true
        modules:
          - name: 'views'
            url: 'console'
            routes:
              - url: '/'                    # url name
                name: 'index'   # function name
                methods: 'GET'
          - name: 'api'
            url: 'api'
            routes:
              - url: '/api/smartbox/actives'                    # url name
                name: 'get_active_devices'   # function name
                methods: 'GET'

  - name:       'main'
    id:     'gws-01'
    service_id: 'gws-01'
    service_type: 'gwserver'
    enable:     true
    class:      'main.MainService'

    fanout:
      - name: 'switch0'
        channels:
          - 'redis/blue_earth.device.message.queue/queue'
          - 'redis/blue_earth.device.message.pub/pubsub'

      - name: 'logging'
        channels:
          - 'redis/trade.log.{service_type}/queue'
          - 'redis/trade.log.{service_type}.{service_id}/pubsub'

    message_chan_address_iot: 'redis/iot_chan.{}/pubsub'    # 接收来自iot控制消息
    message_chan_address: 'redis/message_chan.{}/pubsub'  # 来自外部控制消息

    app_sub_broker: 'localhost:6379:0:'
    servers:
      - name: 'server'
        enable: true
        host: ''
        port: 9088
        heartbeat: 10
        handler_cls:
          class: 'handlers.service.SmartAdapter'
          kwargs:
            max : 100





